"""update course model fields

Revision ID: 928f14bcd08c
Revises: eaee71b7bead
Create Date: 2026-07-07 21:04:26.484099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928f14bcd08c'
down_revision: Union[str, Sequence[str], None] = 'eaee71b7bead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.alter_column('filenames',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_courses_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_is_deleted'))
        batch_op.alter_column('filenames',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('progress')
        batch_op.drop_column('stage')

    # ### end Alembic commands ###
